name: Build & Push Docker Image

on:
  push:
    branches: ["dev"]   # or main for prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/chaulagainrupak/paper-guides:dev
          cache-from: type=registry,ref=ghcr.io/chaulagainrupak/paper-guides:dev
          cache-to: type=registry,mode=max
